name: Docker Image Pusher

on:
  release:
    types:
      - published

jobs:

  build-push:

    runs-on: ubuntu-latest

    steps:
    - name: Extract tag number
      id: extract-tag
      run: |
        echo "::set-output name=tag::$(basename ${GITHUB_REF})"
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REPOSITORY: mamxalf/milih-app
        IMAGE_TAG: ${{ steps.extract-tag.outputs.tag }}
      run: docker build . --file Dockerfile --tag $DOCKER_REPOSITORY:$IMAGE_TAG
