name: Push to docker after Release
on:
  release:
    types:
      - published

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REPOSITORY: mamxalf/milih-app
          IMAGE_TAG: ${{ github.ref }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

          docker buildx build \
            --push \
            --platform linux/amd64,linux/arm64 \
            --tag $DOCKER_REPOSITORY:$IMAGE_TAG .
